# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2026 Gokhan AY <aygkhn@gmail.com>
# Huma Control Center: profile used on battery while "Balanced" is selected; same as powersave
# (CPU in its most efficient mode, turbo off). Plugged in, the normal balanced profile is used.
# A separate profile because tuned-ppd does not allow mapping one profile to two PPD profiles.
# Enabled from Huma Control Center -> Power Saving (huma-control-power battery-profile on).
[main]
summary=Huma Control Center: Balanced on battery, same as powersave
include=powersave
